### PR TITLE
Allow emulator to be used with sunny tripower

### PR DESCRIPTION
**Pull request by cyrill-wyss**
After experimenting with the simulator from https://github.com/RalfOGit/sma-emeter-simulator, it seems that the Sunny Tripower just want more obis data parts. 
This pull requests adds a setting to enable full data mode, compatible with the STP 10.0 (testet on my local inverter). In full data mode, all power totals and the values for each phase are included in the data packet although only with static values.

### CODE REVIEW

**Comment by cyrill-wyss** [comment]
Hi Roeland 
I did the development of this PR in the online Git only. So there might be some spelling mistakes but I hope i got it all right.
Also I could not test the code as i am not used to python or making and deploying docker images for home assistant... If this is not ok, just tell me and I will try to get the know how together and test everything on my local system first.

**Comment by Roeland54** [comment]
Hi thanks for your contribution. I will try to review and test this asap.

**Comment by Roeland54** [comment]
I have created a test version 0.1.1-rc1 that will always send the complete package. You can install it if you add the following repository to your addon store [https://github.com/Roeland54/SMA-Energy-Meter-emulator#next](https://github.com/Roeland54/SMA-Energy-Meter-emulator#next)
Can you test and report back?

**Comment by cyrill-wyss** [comment]
Thanks for creating the test version so quickly. Just tried it out and it works as expected: both my STP 10.0 inverters (Firmware version: 3.4.16.R) are now able to detect and use the emulator.

**Pull request merged**
